package com.lark.imcollab.common.model.enums;

public enum DocumentSemanticActionType {
    INSERT_INLINE_TEXT,
    INSERT_BLOCK_AFTER_ANCHOR,
    INSERT_METADATA_AT_DOCUMENT_HEAD,
    INSERT_SECTION_BEFORE_SECTION,
    APPEND_SECTION_TO_DOCUMENT_END,
    REWRITE_INLINE_TEXT,
    REWRITE_METADATA_AT_DOCUMENT_HEAD,
    REWRITE_SINGLE_BLOCK,
    REWRITE_SECTION_BODY,
    DELETE_INLINE_TEXT,
    DELETE_METADATA_AT_DOCUMENT_HEAD,
    DELETE_BLOCK,
    DELETE_SECTION_BODY,
    DELETE_WHOLE_SECTION,
    MOVE_SECTION,
    MOVE_BLOCK,
    EXPLAIN_ONLY
}
