package com.lark.imcollab.common.model.enums;

public enum DocumentExpectedStateType {
    EXPECT_TEXT_REPLACED,
    EXPECT_BLOCK_REMOVED,
    EXPECT_BLOCK_INSERTED_AFTER,
    EXPECT_SECTION_BODY_REMOVED,
    EXPECT_SECTION_REMOVED,
    EXPECT_METADATA_BLOCK_PRESENT_AT_HEAD,
    EXPECT_NEW_SECTION_BEFORE_TARGET_SECTION,
    EXPECT_CONTENT_APPENDED,
    EXPECT_NO_CHANGE
}
