package com.lark.imcollab.common.model.enums;

public enum DocumentExpectedStateType {
    EXPECT_TEXT_REPLACED,
    EXPECT_BLOCK_REMOVED,
    EXPECT_BLOCK_INSERTED_AFTER,
    EXPECT_SECTION_BODY_REMOVED,
    EXPECT_SECTION_REMOVED,
    EXPECT_METADATA_BLOCK_PRESENT_AT_HEAD,
    EXPECT_NEW_SECTION_BEFORE_TARGET_SECTION,
    EXPECT_CONTENT_APPENDED,
    EXPECT_NO_CHANGE,
    EXPECT_IMAGE_NODE_PRESENT,
    EXPECT_TABLE_NODE_PRESENT,
    EXPECT_WHITEBOARD_NODE_PRESENT,
    EXPECT_MEDIA_NODE_REMOVED,
    EXPECT_LAYOUT_REORDERED
}
