package com.lark.imcollab.common.model.enums;

public enum DocumentStrategyType {
    TEXT_REPLACE,
    BLOCK_INSERT_AFTER,
    BLOCK_REPLACE,
    BLOCK_DELETE,
    BLOCK_MOVE_AFTER,
    APPEND,
    CONTROLLED_HEAD_INSERT,
    CONTROLLED_HEAD_REWRITE,
    CONTROLLED_HEAD_DELETE,
    CONTROLLED_BEFORE_SECTION_INSERT,
    EXPLAIN_ONLY,
    MEDIA_INSERT_AFTER,
    TABLE_INSERT_AFTER,
    TABLE_DATA_REWRITE,
    WHITEBOARD_INSERT_AFTER,
    LAYOUT_REORDER,
    CONVERT_TO_TABLE,
    CONVERT_TO_IMAGE_CARD
}
