package com.lark.imcollab.common.model.enums;

public enum PendingInteractionTypeEnum {
    AWAITING_EXECUTION_CONFIRMATION,
    EXECUTING_PLAN_ADJUSTMENT,
    COMPLETED_TASK_SELECTION,
    COMPLETED_ARTIFACT_SELECTION,
    FOLLOW_UP_CONFLICT_CHOICE,
    CURRENT_TASK_CONTINUATION_CHOICE
}
