package com.lark.imcollab.common.model.enums;

public enum TaskEventTypeEnum {
    INTAKE_ACCEPTED,
    INTENT_ROUTING,
    CLARIFICATION_REQUIRED,
    PLANNING_STARTED,
    PLAN_GATE_CHECKING,
    PLAN_FAILED,
    TASK_RECEIVED,
    CLARIFICATION_REQUESTED,
    CLARIFICATION_ANSWERED,
    INTENT_READY,
    PLAN_READY,
    PLAN_ADJUSTED,
    PLAN_APPROVAL_REQUIRED,
    PLAN_APPROVED,
    STEP_READY,
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    STEP_RETRY_SCHEDULED,
    ARTIFACT_CREATED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_CANCELLED
}
